// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";
import GlobalContextsProvider from "../components/plasmic/blank_project/PlasmicGlobalContextsProvider";

import { TranslationContextProvider } from "../components/plasmic/\u96EA\u9686\u5C11\u6797\u6587\u5316\u534F\u4F1A/PlasmicGlobalVariant__Translation";
import {
  PlasmicContent,
  Head
} from "../components/plasmic/\u96EA\u9686\u5C11\u6797\u6587\u5316\u534F\u4F1A/PlasmicContent";
import type { PageProps } from "gatsby";
export { Head };

function Content({ location, path, params }: PageProps) {
  // Use PlasmicContent to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicContent are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, PlasmicContent is wrapped by your project's global
  // variant context providers. These wrappers may be moved to
  // Gatsby "wrapRootElement" function
  // (https://www.gatsbyjs.com/docs/reference/config-files/gatsby-ssr#wrapRootElement).

  return (
    <TranslationContextProvider value={undefined}>
      <GlobalContextsProvider>
        <PageParamsProvider__
          route={path}
          params={params}
          query={Object.fromEntries(new URLSearchParams(location.search))}
        >
          <PlasmicContent />
        </PageParamsProvider__>
      </GlobalContextsProvider>
    </TranslationContextProvider>
  );
}

export default Content;
