// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";
import GlobalContextsProvider from "../components/plasmic/blank_project/PlasmicGlobalContextsProvider";

import {
  Plasmic少林文化,
  Head
} from "../components/plasmic/\u5409\u9686\u5761\u5C11\u6797\u6587\u5316\u4E2D\u5FC3_back/Plasmic\u5C11\u6797\u6587\u5316";
import type { PageProps } from "gatsby";
export { Head };

function 少林文化({ location, path, params }: PageProps) {
  // Use Plasmic少林文化 to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into Plasmic少林文化 are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.

  return (
    <GlobalContextsProvider>
      <PageParamsProvider__
        route={path}
        params={params}
        query={Object.fromEntries(new URLSearchParams(location.search))}
      >
        <Plasmic少林文化 />
      </PageParamsProvider__>
    </GlobalContextsProvider>
  );
}

export default 少林文化;
