/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sXCRtjYKZPsLyt67ZBQv6B
// Component: _VyosKy2-Hc-

import * as React from "react";

import {
  Link,
  GatsbyLinkProps as LinkProps,
  navigate as __gatsbyNavigate
} from "gatsby";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import PageLayout from "../../PageLayout"; // plasmic-import: v5rlei5vjymQ/component
import { Video } from "@plasmicpkgs/plasmic-basic-components";
import { Embed } from "@plasmicpkgs/plasmic-basic-components";
import { _useGlobalVariants } from "../blank_project/plasmic"; // plasmic-import: sXCRtjYKZPsLyt67ZBQv6B/projectModule
import { _useStyleTokens } from "../blank_project/PlasmicStyleTokensProvider"; // plasmic-import: sXCRtjYKZPsLyt67ZBQv6B/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import * as projectcss from "../blank_project/plasmic.module.css"; // plasmic-import: sXCRtjYKZPsLyt67ZBQv6B/projectcss
import * as sty from "./Plasmic首页.module.css"; // plasmic-import: _VyosKy2-Hc-/css

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export function generateDynamicMetadata($q: any, $ctx: any) {
  return {
    openGraph: {},
    twitter: {
      card: "summary"
    }
  };
}

createPlasmicElementProxy;

export type Plasmic首页__VariantMembers = {};
export type Plasmic首页__VariantsArgs = {};
type VariantPropType = keyof Plasmic首页__VariantsArgs;
export const Plasmic首页__VariantProps = new Array<VariantPropType>();

export type Plasmic首页__ArgsType = {};
type ArgPropType = keyof Plasmic首页__ArgsType;
export const Plasmic首页__ArgProps = new Array<ArgPropType>();

export type Plasmic首页__OverridesType = {
  root?: Flex__<"div">;
  页面格式?: Flex__<typeof PageLayout>;
  首页?: Flex__<"div">;
  htmlVideo?: Flex__<typeof Video>;
  会所地址?: Flex__<"div">;
  embedHtml?: Flex__<typeof Embed>;
};

export interface Default首页Props {
  className?: string;
}

const $$ = {};

export function Head() {
  return <></>;
}

function Plasmic首页__RenderFunc(props: {
  variants: Plasmic首页__VariantsArgs;
  args: Plasmic首页__ArgsType;
  overrides: Plasmic首页__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <PageLayout
            data-plasmic-name={"\u9875\u9762\u683c\u5f0f"}
            data-plasmic-override={overrides.页面格式}
            className={classNames("__wab_instance", sty.页面格式)}
            {...{
              "\u5185\u5bb9": (
                <React.Fragment>
                  <div
                    data-plasmic-name={"\u9996\u9875"}
                    data-plasmic-override={overrides.首页}
                    className={classNames(projectcss.all, sty.首页)}
                  >
                    <Video
                      data-plasmic-name={"htmlVideo"}
                      data-plasmic-override={overrides.htmlVideo}
                      autoPlay={true}
                      className={classNames("__wab_instance", sty.htmlVideo)}
                      controls={false}
                      loop={true}
                      muted={true}
                      playsInline={true}
                      ref={ref => {
                        $refs["htmlVideo"] = ref;
                      }}
                      src={
                        "https://pub-7054b7b403a34f7cbd719e95fda764ac.r2.dev/test_1.webm"
                      }
                    />
                  </div>
                  <div
                    data-plasmic-name={"\u4f1a\u6240\u5730\u5740"}
                    data-plasmic-override={overrides.会所地址}
                    className={classNames(projectcss.all, sty.会所地址)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__qOdB)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pgLcd
                        )}
                      >
                        {"\u5bfb\u627e\u6211\u4eec"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__gEo9O
                        )}
                      >
                        {
                          "3A-08, Jalan Desa Aman 1, Taman Desa Aman, 56100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur"
                        }
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__xjwmk)}
                    >
                      <Embed
                        data-plasmic-name={"embedHtml"}
                        data-plasmic-override={overrides.embedHtml}
                        className={classNames("__wab_instance", sty.embedHtml)}
                        code={
                          '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3983.9992000205793!2d101.739679!3d3.094870899999999!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31cc3591f26d08c9%3A0xebe195d9e240bb6d!2zU2hhb2xpbiBDdWx0dXJhbCBDZW50ZXIgT2YgTWFsYXlzaWEg6ams5p2l6KW_5Lqa5bCR5p6X5paH5YyW5Lit5b-D!5e0!3m2!1sen!2smy!4v1770641307733!5m2!1sen!2smy" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>'
                        }
                      />
                    </div>
                  </div>
                </React.Fragment>
              )
            }}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "\u9875\u9762\u683c\u5f0f",
    "\u9996\u9875",
    "htmlVideo",
    "\u4f1a\u6240\u5730\u5740",
    "embedHtml"
  ],
  页面格式: [
    "\u9875\u9762\u683c\u5f0f",
    "\u9996\u9875",
    "htmlVideo",
    "\u4f1a\u6240\u5730\u5740",
    "embedHtml"
  ],
  首页: ["\u9996\u9875", "htmlVideo"],
  htmlVideo: ["htmlVideo"],
  会所地址: ["\u4f1a\u6240\u5730\u5740", "embedHtml"],
  embedHtml: ["embedHtml"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  页面格式: typeof PageLayout;
  首页: "div";
  htmlVideo: typeof Video;
  会所地址: "div";
  embedHtml: typeof Embed;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  Plasmic首页__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: Plasmic首页__VariantsArgs;
    args?: Plasmic首页__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<Plasmic首页__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<Plasmic首页__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: Plasmic首页__ArgProps,
          internalVariantPropNames: Plasmic首页__VariantProps
        }),
      [props, nodeName]
    );
    return Plasmic首页__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "Plasmic\u9996\u9875";
  } else {
    func.displayName = `Plasmic首页.${nodeName}`;
  }
  return func;
}

export const Plasmic首页 = Object.assign(
  // Top-level Plasmic首页 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    页面格式: makeNodeComponent("\u9875\u9762\u683c\u5f0f"),
    首页: makeNodeComponent("\u9996\u9875"),
    htmlVideo: makeNodeComponent("htmlVideo"),
    会所地址: makeNodeComponent("\u4f1a\u6240\u5730\u5740"),
    embedHtml: makeNodeComponent("embedHtml"),

    // Metadata about props expected for Plasmic首页
    internalVariantProps: Plasmic首页__VariantProps,
    internalArgProps: Plasmic首页__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pagePath: "/",
      searchParams: {},
      params: {}
    })
  }
);

export default Plasmic首页;
/* prettier-ignore-end */
