/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sXCRtjYKZPsLyt67ZBQv6B
// Component: dlaJwa8GeIHa

import * as React from "react";

import {
  Link,
  GatsbyLinkProps as LinkProps,
  navigate as __gatsbyNavigate
} from "gatsby";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import PageLayout from "../../PageLayout"; // plasmic-import: v5rlei5vjymQ/component
import { _useGlobalVariants } from "../blank_project/plasmic"; // plasmic-import: sXCRtjYKZPsLyt67ZBQv6B/projectModule
import { _useStyleTokens } from "../blank_project/PlasmicStyleTokensProvider"; // plasmic-import: sXCRtjYKZPsLyt67ZBQv6B/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import * as projectcss from "../blank_project/plasmic.module.css"; // plasmic-import: sXCRtjYKZPsLyt67ZBQv6B/projectcss
import * as sty from "./Plasmic愿景.module.css"; // plasmic-import: dlaJwa8GeIHa/css

import Icon8Icon from "./icons/PlasmicIcon__Icon8"; // plasmic-import: hDyPSK5AHgyI/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export function generateDynamicMetadata($q: any, $ctx: any) {
  return {
    openGraph: {},
    twitter: {
      card: "summary"
    }
  };
}

createPlasmicElementProxy;

export type Plasmic愿景__VariantMembers = {};
export type Plasmic愿景__VariantsArgs = {};
type VariantPropType = keyof Plasmic愿景__VariantsArgs;
export const Plasmic愿景__VariantProps = new Array<VariantPropType>();

export type Plasmic愿景__ArgsType = {};
type ArgPropType = keyof Plasmic愿景__ArgsType;
export const Plasmic愿景__ArgProps = new Array<ArgPropType>();

export type Plasmic愿景__OverridesType = {
  root?: Flex__<"div">;
  pageLayout?: Flex__<typeof PageLayout>;
  foreground?: Flex__<"div">;
  foreground2?: Flex__<"div">;
  columns?: Flex__<"div">;
};

export interface Default愿景Props {
  className?: string;
}

const $$ = {};

export function Head() {
  return <></>;
}

function Plasmic愿景__RenderFunc(props: {
  variants: Plasmic愿景__VariantsArgs;
  args: Plasmic愿景__ArgsType;
  overrides: Plasmic愿景__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <PageLayout
            data-plasmic-name={"pageLayout"}
            data-plasmic-override={overrides.pageLayout}
            {...{
              "\u5185\u5bb9": (
                <div className={classNames(projectcss.all, sty.freeBox__pakw5)}>
                  <div
                    data-plasmic-name={"foreground"}
                    data-plasmic-override={overrides.foreground}
                    className={classNames(projectcss.all, sty.foreground)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gpSbF
                      )}
                    >
                      {"\u6211\u4eec\u7684\u613f\u666f"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__daF
                      )}
                    >
                      {
                        "\u5728\u591a\u5143\u6587\u5316\u7684\u571f\u58e4\u4e0a\uff0c\u64ad\u6492\u5c11\u6797\u667a\u6167\u7684\u79cd\u5b50"
                      }
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___0VC2C
                      )}
                    >
                      {
                        "\u6211\u4eec\u7684\u957f\u8fdc\u76ee\u6807\uff0c\u662f\u5728\u9a6c\u6765\u897f\u4e9a\u5efa\u7acb\u4e00\u4e2a\u5177\u6709\u516c\u4fe1\u529b\u548c\u5f71\u54cd\u529b\u7684\u5c11\u6797\u6587\u5316\u5e73\u53f0\u3002"
                      }
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"foreground2"}
                    data-plasmic-override={overrides.foreground2}
                    className={classNames(projectcss.all, sty.foreground2)}
                  >
                    <div
                      data-plasmic-name={"columns"}
                      data-plasmic-override={overrides.columns}
                      className={classNames(projectcss.all, sty.columns)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__obifa
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__u4Pa1
                          )}
                        >
                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__kdSgq
                              )}
                            >
                              <Icon8Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__tpTi1
                                )}
                                role={"img"}
                              />
                            </div>
                          ) : null}
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__oa8I9
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__wZzL
                              )}
                            >
                              {"\u5b88\u62a4\u4f20\u7edf"}
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__sePzB
                              )}
                            >
                              {
                                "\u539f\u6c41\u539f\u5473\u5730\u4f20\u627f\u5c11\u6797\u5bfa\u5343\u5e74\u7684\u6587\u5316\u7cbe\u9ad3"
                              }
                            </div>
                          </div>
                        </div>
                      </div>
                      <div
                        className={classNames(projectcss.all, sty.column__kl0K)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__afbbT
                          )}
                        >
                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox___1HSlq
                              )}
                            >
                              <Icon8Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__dwQ2I
                                )}
                                role={"img"}
                              />
                            </div>
                          ) : null}
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__t1C3W
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__pl20H
                              )}
                            >
                              {"\u878d\u5408\u672c\u571f"}
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__wBt8I
                              )}
                            >
                              {
                                "\u4e0e\u9a6c\u6765\u897f\u4e9a\u591a\u5143\u79cd\u65cf\u3001\u591a\u5143\u6587\u5316\u7684\u793e\u4f1a\u548c\u8c10\u5171\u751f\uff0c\u521b\u65b0\u53d1\u5c55\u3002"
                              }
                            </div>
                          </div>
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__pqL5Z
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__hmLtL
                          )}
                        >
                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__dem9O
                              )}
                            >
                              <Icon8Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__ohs1
                                )}
                                role={"img"}
                              />
                            </div>
                          ) : null}
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__scMcd
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__knLl3
                              )}
                            >
                              {"\u56de\u9988\u793e\u4f1a"}
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__kajFm
                              )}
                            >
                              {
                                "\u901a\u8fc7\u6301\u7eed\u7684\u52aa\u529b\u548c\u793e\u533a\u670d\u52a1\uff0c\u57f9\u517b\u51fa\u66f4\u591a\u62e5\u6709\u5f3a\u5065\u4f53\u9b44\u3001\u5e73\u548c\u5185\u5fc3\u4e0e\u9ad8\u5c1a\u54c1\u683c\u7684\u4e2a\u4f53\uff0c\u4e3a\u793e\u4f1a\u7684\u548c\u8c10\u4e0e\u8fdb\u6b65\u8d21\u732e\u529b\u91cf\u3002"
                              }
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              )
            }}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "pageLayout", "foreground", "foreground2", "columns"],
  pageLayout: ["pageLayout", "foreground", "foreground2", "columns"],
  foreground: ["foreground"],
  foreground2: ["foreground2", "columns"],
  columns: ["columns"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  pageLayout: typeof PageLayout;
  foreground: "div";
  foreground2: "div";
  columns: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  Plasmic愿景__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: Plasmic愿景__VariantsArgs;
    args?: Plasmic愿景__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<Plasmic愿景__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<Plasmic愿景__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: Plasmic愿景__ArgProps,
          internalVariantPropNames: Plasmic愿景__VariantProps
        }),
      [props, nodeName]
    );
    return Plasmic愿景__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "Plasmic\u613f\u666f";
  } else {
    func.displayName = `Plasmic愿景.${nodeName}`;
  }
  return func;
}

export const Plasmic愿景 = Object.assign(
  // Top-level Plasmic愿景 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    pageLayout: makeNodeComponent("pageLayout"),
    foreground: makeNodeComponent("foreground"),
    foreground2: makeNodeComponent("foreground2"),
    columns: makeNodeComponent("columns"),

    // Metadata about props expected for Plasmic愿景
    internalVariantProps: Plasmic愿景__VariantProps,
    internalArgProps: Plasmic愿景__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pagePath: "/愿景",
      searchParams: {},
      params: {}
    })
  }
);

export default Plasmic愿景;
/* prettier-ignore-end */
