/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sXCRtjYKZPsLyt67ZBQv6B
// Component: _VyosKy2-Hc-

import * as React from "react";

import {
  Link,
  GatsbyLinkProps as LinkProps,
  navigate as __gatsbyNavigate
} from "gatsby";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import PageLayout from "../../PageLayout"; // plasmic-import: v5rlei5vjymQ/component
import { Video } from "@plasmicpkgs/plasmic-basic-components";
import Button from "../../Button"; // plasmic-import: 3Vko89ihbPRA/component
import Button2 from "../../Button2"; // plasmic-import: ZVEi9idvlzT1/component
import { Embed } from "@plasmicpkgs/plasmic-basic-components";
import { _useGlobalVariants } from "../blank_project/plasmic"; // plasmic-import: sXCRtjYKZPsLyt67ZBQv6B/projectModule
import { _useStyleTokens } from "../blank_project/PlasmicStyleTokensProvider"; // plasmic-import: sXCRtjYKZPsLyt67ZBQv6B/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import * as projectcss from "../blank_project/plasmic.module.css"; // plasmic-import: sXCRtjYKZPsLyt67ZBQv6B/projectcss
import * as sty from "./Plasmic首页.module.css"; // plasmic-import: _VyosKy2-Hc-/css

import CircleIcon from "../blank_project/icons/PlasmicIcon__Circle"; // plasmic-import: gZuwXhxC2QAl/icon
import ChevronDownIcon from "../blank_project/icons/PlasmicIcon__ChevronDown"; // plasmic-import: wjngPrVRJ2Ty/icon
import EyeIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__Eye"; // plasmic-import: a8G7UBLzxa_z/icon
import PhoneIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__Phone"; // plasmic-import: EOOfRsOwbYR2/icon
import image4JFKqPQlsRqvV from "./images/image4.png"; // plasmic-import: jFKqPQlsRqvV/picture
import image5NuzrUiBqxMr1 from "./images/image5.png"; // plasmic-import: nuzrUiBqxMr1/picture
import image9WuJyUNs2DAF from "./images/image9.png"; // plasmic-import: WuJyUNs2dA-f/picture
import image6NQqklGGuvZp from "./images/image6.png"; // plasmic-import: NQqklGGuv-zp/picture

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export function generateDynamicMetadata($q: any, $ctx: any) {
  return {
    openGraph: {},
    twitter: {
      card: "summary"
    }
  };
}

createPlasmicElementProxy;

export type Plasmic首页__VariantMembers = {};
export type Plasmic首页__VariantsArgs = {};
type VariantPropType = keyof Plasmic首页__VariantsArgs;
export const Plasmic首页__VariantProps = new Array<VariantPropType>();

export type Plasmic首页__ArgsType = {};
type ArgPropType = keyof Plasmic首页__ArgsType;
export const Plasmic首页__ArgProps = new Array<ArgPropType>();

export type Plasmic首页__OverridesType = {
  root?: Flex__<"div">;
  页面格式?: Flex__<typeof PageLayout>;
  标题?: Flex__<"div">;
  htmlVideo?: Flex__<typeof Video>;
  雪隆少林文化协会?: Flex__<"div">;
  会所地址?: Flex__<"div">;
  embedHtml?: Flex__<typeof Embed>;
};

export interface Default首页Props {
  className?: string;
}

const $$ = {};

export function Head() {
  return <></>;
}

function Plasmic首页__RenderFunc(props: {
  variants: Plasmic首页__VariantsArgs;
  args: Plasmic首页__ArgsType;
  overrides: Plasmic首页__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <PageLayout
            data-plasmic-name={"\u9875\u9762\u683c\u5f0f"}
            data-plasmic-override={overrides.页面格式}
            className={classNames("__wab_instance", sty.页面格式)}
            {...{
              "\u5185\u5bb9": (
                <React.Fragment>
                  <div
                    data-plasmic-name={"\u6807\u9898"}
                    data-plasmic-override={overrides.标题}
                    className={classNames(projectcss.all, sty.标题)}
                  >
                    <Video
                      data-plasmic-name={"htmlVideo"}
                      data-plasmic-override={overrides.htmlVideo}
                      autoPlay={true}
                      className={classNames("__wab_instance", sty.htmlVideo)}
                      controls={false}
                      loop={true}
                      playsInline={true}
                      preload={"auto"}
                      ref={ref => {
                        $refs["htmlVideo"] = ref;
                      }}
                      src={
                        "https://pub-7054b7b403a34f7cbd719e95fda764ac.r2.dev/AQMNS20S3GXqwCEN8vBmwyWCXdw2CpkVlV_if6FSJzWtBuk5NA8rYsa-NDXv2nBkPgrrjuPevTPDxOTq9Tqm2JkR-gxioitoPcubygEjVKEr4Q.mp4"
                      }
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__msCLl)}
                    >
                      <div
                        data-plasmic-name={
                          "\u96ea\u9686\u5c11\u6797\u6587\u5316\u534f\u4f1a"
                        }
                        data-plasmic-override={overrides.雪隆少林文化协会}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.雪隆少林文化协会
                        )}
                      >
                        {"\u96ea\u9686\u5c11\u6797\u6587\u5316\u534f\u4f1a"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___4NxlG
                        )}
                      >
                        {
                          "\u7985\u6b66\u5408\u4e00 \u00b7 \u8eab\u5fc3\u5171\u4fee \u00b7 \u670d\u52a1\u793e\u7fa4"
                        }
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__qyYs
                        )}
                      >
                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button__fd1Ab
                          )}
                          color={"neutral"}
                          label={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__pnKq7
                              )}
                            >
                              {"\u63a2\u7d22\u8bfe\u7a0b"}
                            </div>
                          }
                          type={"soft"}
                        />

                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button__og8VI
                          )}
                          label={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__mkgZc
                              )}
                            >
                              {"\u6210\u4e3a\u4f1a\u5458"}
                            </div>
                          }
                          type={"soft"}
                        />
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__sd0Wq)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___3Dm4B
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobile")
                        ? "\u4ee5\u6b66\u4fee\u7985\uff0c\n\u4ee5\u7985\u5bfc\u6b66"
                        : "\u4ee5\u6b66\u4fee\u7985\uff0c\u4ee5\u7985\u5bfc\u6b66"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__f4ShQ
                      )}
                    >
                      {
                        "\u6211\u4eec\u662f\u9a6c\u6765\u897f\u4e9a\u96ea\u5170\u83aa\u53ca\u5409\u9686\u5761\u5730\u533a\u4e00\u4e2a\u975e\u8425\u5229\u7684\u6587\u5316\u7ec4\u7ec7\u3002\u6211\u4eec\u81f4\u529b\u4e8e\u5c06\u53e4\u8001\u7684\u5c11\u6797\u667a\u6167\u2014\u2014\u7985\u3001\u6b66\u3001\u533b\u3001\u827a\u2014\u2014\u878d\u5165\u73b0\u4ee3\u751f\u6d3b\uff0c\u5e2e\u52a9\u4eba\u4eec\u5efa\u7acb\u8eab\u5fc3\u7684\u548c\u8c10\u4e0e\u529b\u91cf\uff0c\u5171\u540c\u6784\u5efa\u4e00\u4e2a\u66f4\u5177\u5173\u6000\u7684\u793e\u533a\u3002"
                      }
                    </div>
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__eIjZq
                      )}
                      flatSide={[]}
                      label={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__lwDdO
                          )}
                        >
                          {"\u4e86\u89e3\u66f4\u591a"}
                        </div>
                      }
                      linkTo={`/关于我们`}
                      size={"large"}
                      type={"bordered"}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__jwTge)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___7HH9
                      )}
                    >
                      {"\u56db\u5927\u57fa\u77f3"}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.columns__mbIL)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__fjyem
                        )}
                      >
                        <h1
                          className={classNames(
                            projectcss.all,
                            projectcss.h1,
                            projectcss.__wab_text,
                            sty.h1__aRnQk
                          )}
                        >
                          {"\u7985"}
                        </h1>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___6Wy5K
                          )}
                        >
                          {
                            "\u51c0\u5316\u5fc3\u7075\uff0c\u57f9\u517b\u5185\u5728\u7684\u89c9\u77e5\u4e0e\u5b9a\u529b\uff0c\u4e8e\u52a8\u9759\u4e4b\u4e2d\u89c1\u667a\u6167\u3002"
                          }
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__eAbL0
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__qx5Ty)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: image4JFKqPQlsRqvV,
                            fullWidth: 1024,
                            fullHeight: 1024,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__nzxAw
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__q7Ssq)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: image5NuzrUiBqxMr1,
                            fullWidth: 1024,
                            fullHeight: 1024,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___0KMdY
                        )}
                      >
                        <h1
                          className={classNames(
                            projectcss.all,
                            projectcss.h1,
                            projectcss.__wab_text,
                            sty.h1__cllMg
                          )}
                        >
                          {"\u6b66"}
                        </h1>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__maNf3
                          )}
                        >
                          {
                            "\u953b\u70bc\u4f53\u9b44\uff0c\u78e8\u7ec3\u575a\u97e7\u4e0d\u62d4\u7684\u610f\u5fd7\uff0c\u5728\u6c57\u6c34\u4e2d\u91cd\u5851\u81ea\u6211\u3002"
                          }
                        </div>
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___55FQx)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.columns___2N1UQ
                      )}
                    >
                      <div
                        className={classNames(projectcss.all, sty.column__lCrn)}
                      >
                        <h1
                          className={classNames(
                            projectcss.all,
                            projectcss.h1,
                            projectcss.__wab_text,
                            sty.h1___15BAo
                          )}
                        >
                          {"\u533b"}
                        </h1>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__tm6Ic
                          )}
                        >
                          {
                            "\u8c03\u548c\u6c14\u8840\uff0c\u901a\u8fc7\u547c\u5438\u6cd5\u3001\u5bfc\u5f15\u672f\u7b49\u4f20\u7edf\u517b\u751f\u65b9\u5f0f\uff0c\u5b88\u62a4\u8eab\u5fc3\u5065\u5eb7\u3002"
                          }
                        </div>
                      </div>
                      <div
                        className={classNames(projectcss.all, sty.column__aEH9)}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img___3Kin)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: image9WuJyUNs2DAF,
                            fullWidth: 1536,
                            fullHeight: 1024,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__e5U24
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img___8Emgm)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: image6NQqklGGuvZp,
                            fullWidth: 1536,
                            fullHeight: 1024,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__dBzK7
                        )}
                      >
                        <h1
                          className={classNames(
                            projectcss.all,
                            projectcss.h1,
                            projectcss.__wab_text,
                            sty.h1__fr0Lx
                          )}
                        >
                          {"\u827a"}
                        </h1>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__pqBdA
                          )}
                        >
                          {
                            "\u6db5\u517b\u6027\u60c5\uff0c\u5728\u4f20\u7edf\u6587\u5316\u7684\u718f\u9676\u4e2d\uff0c\u63d0\u5347\u5ba1\u7f8e\u4e0e\u751f\u6d3b\u54c1\u8d28\u3002"
                          }
                        </div>
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__yIKzc)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___0Jtod
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___86Vpp
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobile")
                          ? "\u5b88\u62a4\u4f20\u7edf\uff0c\n\u5f00\u521b\u672a\u6765"
                          : "\u5b88\u62a4\u4f20\u7edf\uff0c\u5f00\u521b\u672a\u6765"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__fUbuB
                        )}
                      >
                        {
                          "\u6211\u4eec\u76f8\u4fe1\uff0c\u771f\u6b63\u7684\u529b\u91cf\u6e90\u4e8e\u8eab\u5fc3\u7684\u548c\u8c10\u4e0e\u54c1\u683c\u7684\u5b8c\u5584\u3002\u52a0\u5165\u6211\u4eec\uff0c\u4e00\u8d77\u63a2\u7d22\u8fd9\u6761\u901a\u5f80\u5065\u5eb7\u3001\u5e73\u9759\u4e0e\u667a\u6167\u7684\u5c11\u6797\u4e4b\u8def\u3002"
                        }
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__fle04
                        )}
                      >
                        <Button2
                          className={classNames(
                            "__wab_instance",
                            sty.button2__niZ2S
                          )}
                          color={"black"}
                          end={
                            <EyeIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__tre8X
                              )}
                              role={"img"}
                            />
                          }
                          iconEnd={true}
                          label={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___1Qed2
                              )}
                            >
                              {"\u67e5\u770b\u8bfe\u7a0b\u8be6\u60c5"}
                            </div>
                          }
                          size={"large"}
                          start={
                            <CircleIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__ynHd7
                              )}
                              role={"img"}
                            />
                          }
                        />

                        <Button2
                          className={classNames(
                            "__wab_instance",
                            sty.button2__mtdq4
                          )}
                          color={"black"}
                          end={
                            <PhoneIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__xCyBt
                              )}
                              role={"img"}
                            />
                          }
                          iconEnd={true}
                          label={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__vtlhM
                              )}
                            >
                              {"\u8054\u7cfb\u6211\u4eec"}
                            </div>
                          }
                          size={"large"}
                          start={
                            <CircleIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__vskQe
                              )}
                              role={"img"}
                            />
                          }
                        />
                      </div>
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"\u4f1a\u6240\u5730\u5740"}
                    data-plasmic-override={overrides.会所地址}
                    className={classNames(projectcss.all, sty.会所地址)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__qOdB)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pgLcd
                        )}
                      >
                        {"\u5bfb\u627e\u6211\u4eec"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__gEo9O
                        )}
                      >
                        {
                          "3A-08, Jalan Desa Aman 1, Taman Desa Aman, \n56100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur"
                        }
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__xjwmk)}
                    >
                      <Embed
                        data-plasmic-name={"embedHtml"}
                        data-plasmic-override={overrides.embedHtml}
                        className={classNames("__wab_instance", sty.embedHtml)}
                        code={
                          '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3983.9992000205793!2d101.739679!3d3.094870899999999!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31cc3591f26d08c9%3A0xebe195d9e240bb6d!2zU2hhb2xpbiBDdWx0dXJhbCBDZW50ZXIgT2YgTWFsYXlzaWEg6ams5p2l6KW_5Lqa5bCR5p6X5paH5YyW5Lit5b-D!5e0!3m2!1sen!2smy!4v1770641307733!5m2!1sen!2smy" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>'
                        }
                      />
                    </div>
                  </div>
                </React.Fragment>
              )
            }}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "\u9875\u9762\u683c\u5f0f",
    "\u6807\u9898",
    "htmlVideo",
    "\u96ea\u9686\u5c11\u6797\u6587\u5316\u534f\u4f1a",
    "\u4f1a\u6240\u5730\u5740",
    "embedHtml"
  ],
  页面格式: [
    "\u9875\u9762\u683c\u5f0f",
    "\u6807\u9898",
    "htmlVideo",
    "\u96ea\u9686\u5c11\u6797\u6587\u5316\u534f\u4f1a",
    "\u4f1a\u6240\u5730\u5740",
    "embedHtml"
  ],
  标题: [
    "\u6807\u9898",
    "htmlVideo",
    "\u96ea\u9686\u5c11\u6797\u6587\u5316\u534f\u4f1a"
  ],
  htmlVideo: ["htmlVideo"],
  雪隆少林文化协会: ["\u96ea\u9686\u5c11\u6797\u6587\u5316\u534f\u4f1a"],
  会所地址: ["\u4f1a\u6240\u5730\u5740", "embedHtml"],
  embedHtml: ["embedHtml"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  页面格式: typeof PageLayout;
  标题: "div";
  htmlVideo: typeof Video;
  雪隆少林文化协会: "div";
  会所地址: "div";
  embedHtml: typeof Embed;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  Plasmic首页__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: Plasmic首页__VariantsArgs;
    args?: Plasmic首页__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<Plasmic首页__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<Plasmic首页__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: Plasmic首页__ArgProps,
          internalVariantPropNames: Plasmic首页__VariantProps
        }),
      [props, nodeName]
    );
    return Plasmic首页__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "Plasmic\u9996\u9875";
  } else {
    func.displayName = `Plasmic首页.${nodeName}`;
  }
  return func;
}

export const Plasmic首页 = Object.assign(
  // Top-level Plasmic首页 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    页面格式: makeNodeComponent("\u9875\u9762\u683c\u5f0f"),
    标题: makeNodeComponent("\u6807\u9898"),
    htmlVideo: makeNodeComponent("htmlVideo"),
    雪隆少林文化协会: makeNodeComponent(
      "\u96ea\u9686\u5c11\u6797\u6587\u5316\u534f\u4f1a"
    ),
    会所地址: makeNodeComponent("\u4f1a\u6240\u5730\u5740"),
    embedHtml: makeNodeComponent("embedHtml"),

    // Metadata about props expected for Plasmic首页
    internalVariantProps: Plasmic首页__VariantProps,
    internalArgProps: Plasmic首页__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pagePath: "/",
      searchParams: {},
      params: {}
    })
  }
);

export default Plasmic首页;
/* prettier-ignore-end */
