/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sXCRtjYKZPsLyt67ZBQv6B
// Component: mNk97f8Cyt8o

import * as React from "react";

import {
  Link,
  GatsbyLinkProps as LinkProps,
  navigate as __gatsbyNavigate
} from "gatsby";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import PageLayout from "../../PageLayout"; // plasmic-import: v5rlei5vjymQ/component
import { _useGlobalVariants } from "../blank_project/plasmic"; // plasmic-import: sXCRtjYKZPsLyt67ZBQv6B/projectModule
import { _useStyleTokens } from "../blank_project/PlasmicStyleTokensProvider"; // plasmic-import: sXCRtjYKZPsLyt67ZBQv6B/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import * as projectcss from "../blank_project/plasmic.module.css"; // plasmic-import: sXCRtjYKZPsLyt67ZBQv6B/projectcss
import * as sty from "./PlasmicContent.module.css"; // plasmic-import: mNk97f8Cyt8o/css

import Icon6Icon from "./icons/PlasmicIcon__Icon6"; // plasmic-import: Eif9-yi5c7zy/icon
import Icon7Icon from "./icons/PlasmicIcon__Icon7"; // plasmic-import: T_Bx_3Wa6Re9/icon
import Icon9Icon from "./icons/PlasmicIcon__Icon9"; // plasmic-import: yQFk0xVjJmXV/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export function generateDynamicMetadata($q: any, $ctx: any) {
  return {
    openGraph: {},
    twitter: {
      card: "summary"
    }
  };
}

createPlasmicElementProxy;

export type PlasmicContent__VariantMembers = {};
export type PlasmicContent__VariantsArgs = {};
type VariantPropType = keyof PlasmicContent__VariantsArgs;
export const PlasmicContent__VariantProps = new Array<VariantPropType>();

export type PlasmicContent__ArgsType = {};
type ArgPropType = keyof PlasmicContent__ArgsType;
export const PlasmicContent__ArgProps = new Array<ArgPropType>();

export type PlasmicContent__OverridesType = {
  root?: Flex__<"div">;
  pageLayout?: Flex__<typeof PageLayout>;
  header?: Flex__<"header">;
  text?: Flex__<"div">;
  h1?: Flex__<"h1">;
  img?: Flex__<typeof PlasmicImg__>;
  footer?: Flex__<"footer">;
};

export interface DefaultContentProps {
  className?: string;
}

const $$ = {};

export function Head() {
  return <></>;
}

function PlasmicContent__RenderFunc(props: {
  variants: PlasmicContent__VariantsArgs;
  args: PlasmicContent__ArgsType;
  overrides: PlasmicContent__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <PageLayout
            data-plasmic-name={"pageLayout"}
            data-plasmic-override={overrides.pageLayout}
            {...{
              "\u5185\u5bb9": (
                <div className={classNames(projectcss.all, sty.freeBox__o5GKu)}>
                  <header
                    data-plasmic-name={"header"}
                    data-plasmic-override={overrides.header}
                    className={classNames(projectcss.all, sty.header)}
                  />

                  <section
                    className={classNames(projectcss.all, sty.section___1Qeuu)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__it7Ow)}
                    >
                      <div
                        data-plasmic-name={"text"}
                        data-plasmic-override={overrides.text}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text
                        )}
                      >
                        {"Enter some text"}
                      </div>
                      <h1
                        data-plasmic-name={"h1"}
                        data-plasmic-override={overrides.h1}
                        className={classNames(
                          projectcss.all,
                          projectcss.h1,
                          projectcss.__wab_text,
                          sty.h1
                        )}
                      >
                        {"\u5c11\u6797\u6587\u5316"}
                      </h1>
                      <p
                        className={classNames(
                          projectcss.all,
                          projectcss.p,
                          projectcss.__wab_text,
                          sty.p__hff0X
                        )}
                      >
                        {"\u7985 \u00b7 \u6b66 \u00b7 \u533b \u00b7 \u827a"}
                      </p>
                    </div>
                  </section>
                  <section
                    className={classNames(projectcss.all, sty.section__kICv)}
                  >
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__lXgnG
                      )}
                    >
                      {"\u6587\u5316\u6838\u5fc3"}
                    </h2>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__fMvs2)}
                      style={{
                        gridTemplateColumns:
                          "repeat(auto-fit,minmax(280px,1fr))"
                      }}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___19ZWw
                        )}
                      >
                        <Icon6Icon
                          className={classNames(projectcss.all, sty.svg__xxwT2)}
                          role={"img"}
                          style={{ fill: "#d4af37" }}
                        />

                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3___0DV2
                          )}
                        >
                          {"\u7985\u5b97\u7cbe\u795e"}
                        </h3>
                        <p
                          className={classNames(
                            projectcss.all,
                            projectcss.p,
                            projectcss.__wab_text,
                            sty.p__ojl0V
                          )}
                        >
                          {
                            "\u5c11\u6797\u6587\u5316\u7684\u7075\u9b42\u662f\u7985\u3002\u5f3a\u8c03\u4e13\u6ce8\u3001\u89c9\u77e5\u4e0e\u5185\u5fc3\u5e73\u9759\uff0c\u5c06\u4fee\u884c\u878d\u5165\u65e5\u5e38\u751f\u6d3b\u3002"
                          }
                        </p>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__eQgar
                        )}
                      >
                        <Icon7Icon
                          className={classNames(projectcss.all, sty.svg__a68Rz)}
                          role={"img"}
                          style={{ fill: "#d4af37" }}
                        />

                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__eQvAk
                          )}
                        >
                          {"\u6b66\u672f\u4e4b\u9053"}
                        </h3>
                        <p
                          className={classNames(
                            projectcss.all,
                            projectcss.p,
                            projectcss.__wab_text,
                            sty.p__hQm5Z
                          )}
                        >
                          {
                            "\u5c11\u6797\u529f\u592b\u4e0d\u4ec5\u662f\u683c\u6597\u6280\u827a\uff0c\u66f4\u662f\u8eab\u5fc3\u5408\u4e00\u7684\u4fee\u70bc\u65b9\u5f0f\u3002"
                          }
                        </p>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__eiC5K
                        )}
                      >
                        <Icon9Icon
                          className={classNames(projectcss.all, sty.svg__lfswm)}
                          role={"img"}
                          style={{ fill: "#d4af37" }}
                        />

                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__da8YJ
                          )}
                        >
                          {"\u4f20\u7edf\u533b\u5b66"}
                        </h3>
                        <p
                          className={classNames(
                            projectcss.all,
                            projectcss.p,
                            projectcss.__wab_text,
                            sty.p___0Pehx
                          )}
                        >
                          {
                            "\u7ed3\u5408\u6c14\u529f\u4e0e\u517b\u751f\u7406\u5ff5\uff0c\u8ffd\u6c42\u8eab\u5fc3\u5e73\u8861\u4e0e\u5065\u5eb7\u3002"
                          }
                        </p>
                      </div>
                    </div>
                  </section>
                  <section
                    className={classNames(projectcss.all, sty.section__ekMuj)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___5JghO
                      )}
                    >
                      <PlasmicImg__
                        data-plasmic-name={"img"}
                        data-plasmic-override={overrides.img}
                        alt={""}
                        className={classNames(sty.img)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={"https://picsum.photos/600/800?random=2"}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__pnvCc)}
                    >
                      <h2
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          projectcss.__wab_text,
                          sty.h2__u2Dyl
                        )}
                      >
                        {"\u5343\u5e74\u4f20\u627f"}
                      </h2>
                      <p
                        className={classNames(
                          projectcss.all,
                          projectcss.p,
                          projectcss.__wab_text,
                          sty.p__yvc7E
                        )}
                      >
                        {
                          "\u5c11\u6797\u6587\u5316\u8d77\u6e90\u4e8e\u5d69\u5c71\u5c11\u6797\u5bfa\uff0c\u5df2\u67091500\u591a\u5e74\u5386\u53f2\u3002\n        \u5b83\u878d\u5408\u4f5b\u6559\u54f2\u5b66\u4e0e\u6b66\u672f\u4fee\u884c\uff0c\u662f\u4e2d\u56fd\u6587\u5316\u7684\u91cd\u8981\u8c61\u5f81\u3002"
                        }
                      </p>
                    </div>
                  </section>
                  <section
                    className={classNames(projectcss.all, sty.section__nJcui)}
                  >
                    <p
                      className={classNames(
                        projectcss.all,
                        projectcss.p,
                        projectcss.__wab_text,
                        sty.p__aI7Fq
                      )}
                    >
                      {
                        "\u201c\u4ee5\u7985\u5165\u6b66\uff0c\u4ee5\u6b66\u609f\u7985\u201d"
                      }
                    </p>
                  </section>
                  <section
                    className={classNames(projectcss.all, sty.section__ggmJy)}
                  >
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__eOtqR
                      )}
                    >
                      {"\u6587\u5316\u5f71\u54cd"}
                    </h2>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__jpFup)}
                      style={{
                        gridTemplateColumns:
                          "repeat(auto-fit,minmax(280px,1fr))"
                      }}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__qhPiJ
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__sEyxs
                          )}
                        >
                          {"\u7cbe\u795e\u4fee\u884c"}
                        </h3>
                        <p
                          className={classNames(
                            projectcss.all,
                            projectcss.p,
                            projectcss.__wab_text,
                            sty.p__ezxLq
                          )}
                        >
                          {
                            "\u57f9\u517b\u7eaa\u5f8b\u3001\u81ea\u5f8b\u4e0e\u4e13\u6ce8\u3002"
                          }
                        </p>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__rkihP
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3___4NnBc
                          )}
                        >
                          {"\u8eab\u4f53\u8bad\u7ec3"}
                        </h3>
                        <p
                          className={classNames(
                            projectcss.all,
                            projectcss.p,
                            projectcss.__wab_text,
                            sty.p___24CQc
                          )}
                        >
                          {
                            "\u8ffd\u6c42\u529b\u91cf\u4e0e\u67d4\u97e7\u7684\u5e73\u8861\u3002"
                          }
                        </p>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__nKwTi
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__aVT
                          )}
                        >
                          {"\u4e16\u754c\u4f20\u64ad"}
                        </h3>
                        <p
                          className={classNames(
                            projectcss.all,
                            projectcss.p,
                            projectcss.__wab_text,
                            sty.p__c6Qwm
                          )}
                        >
                          {
                            "\u5c11\u6797\u6587\u5316\u5df2\u6210\u4e3a\u5168\u7403\u8ba4\u77e5\u7684\u4e1c\u65b9\u7b26\u53f7\u3002"
                          }
                        </p>
                      </div>
                    </div>
                  </section>
                  <footer
                    data-plasmic-name={"footer"}
                    data-plasmic-override={overrides.footer}
                    className={classNames(projectcss.all, sty.footer)}
                  >
                    <p
                      className={classNames(
                        projectcss.all,
                        projectcss.p,
                        projectcss.__wab_text,
                        sty.p__hbkxv
                      )}
                    >
                      {"\u00a9 \u5c11\u6797\u6587\u5316\u5c55\u793a"}
                    </p>
                  </footer>
                </div>
              )
            }}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "pageLayout", "header", "text", "h1", "img", "footer"],
  pageLayout: ["pageLayout", "header", "text", "h1", "img", "footer"],
  header: ["header"],
  text: ["text"],
  h1: ["h1"],
  img: ["img"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  pageLayout: typeof PageLayout;
  header: "header";
  text: "div";
  h1: "h1";
  img: typeof PlasmicImg__;
  footer: "footer";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicContent__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicContent__VariantsArgs;
    args?: PlasmicContent__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicContent__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicContent__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicContent__ArgProps,
          internalVariantPropNames: PlasmicContent__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicContent__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicContent";
  } else {
    func.displayName = `PlasmicContent.${nodeName}`;
  }
  return func;
}

export const PlasmicContent = Object.assign(
  // Top-level PlasmicContent renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    pageLayout: makeNodeComponent("pageLayout"),
    header: makeNodeComponent("header"),
    text: makeNodeComponent("text"),
    h1: makeNodeComponent("h1"),
    img: makeNodeComponent("img"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicContent
    internalVariantProps: PlasmicContent__VariantProps,
    internalArgProps: PlasmicContent__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pagePath: "/content",
      searchParams: {},
      params: {}
    })
  }
);

export default PlasmicContent;
/* prettier-ignore-end */
